In [1]:
import pandas as pd

data= {
    "name": ["ayush", "pratik", "piyush","soham", "nishant"],
    "age": [None , 13, 15, None, 18],
    "grades": [80, None, 89, 78, None]
}
df= pd.DataFrame(data)
print(df)
df["age"].fillna(df["age"].mean(), inplace= True )
df["grades"].fillna(df["grades"].mean(), inplace= True)
df

      name   age  grades
0    ayush   NaN    80.0
1   pratik  13.0     NaN
2   piyush  15.0    89.0
3    soham   NaN    78.0
4  nishant  18.0     NaN

C:\Users\ayush\AppData\Local\Temp\ipykernel_11608\1140863655.py:10: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["age"].fillna(df["age"].mean(), inplace= True )
C:\Users\ayush\AppData\Local\Temp\ipykernel_11608\1140863655.py:11: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["grades"].fillna(df["grades"].mean(), inplace= True)

      name   age  grades
0    ayush   NaN    80.0
1   pratik  13.0     NaN
2   piyush  15.0    89.0
3    soham   NaN    78.0
4  nishant  18.0     NaN

In [3]:
nullvalue = df.isnull().sum()
print(nullvalue)

name      0
age       2
grades    2
dtype: int64

In [4]:
drop_na= df.dropna()
print(drop_na)

     name   age  grades
2  piyush  15.0    89.0

In [12]:
df["age"].fillna(df["age"].mean(), inplace= True )
df["grades"].fillna(df["grades"].mean(), inplace= True)
df

C:\Users\ayush\AppData\Local\Temp\ipykernel_4196\722766315.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["age"].fillna(df["age"].mean(), inplace= True )
C:\Users\ayush\AppData\Local\Temp\ipykernel_4196\722766315.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["grades"].fillna(df["grades"].mean(), inplace= True)

      name   age  grades
0    ayush   NaN    80.0
1   pratik  13.0     NaN
2   piyush  15.0    89.0
3    soham   NaN    78.0
4  nishant  18.0     NaN