In [2]:
import requests 
import pandas as pd 
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

In [ ]:
url = "https://metamorphosis.youv.ai/api/billing/sales-period?user_map_id=70697&start_date=2026-04-01&end_date=2026-04-30"

response = requests.get(url)

data = response.json()
print(data)
print(type(data))
print(data.keys())
for key in data.keys():
    print(key , "->", type(data[key]))
for key in data:
    print(key , type(data[key]))
print(data["data"][0])

{'success': True, 'source': 'docexa_billing_only', 'meta': {'user_map_id': 70697, 'start_date': '2026-04-01', 'end_date': '2026-04-30', 'payment_range': {'gte': '2026-04-01 00:00:00', 'lt': '2026-05-01 00:00:00'}, 'location': {'user_map_id': 70697, 'clinic_name': 'Metamorphosis Aesthetic Pvt. Ltd.', 'city': 'Greater kailash', 'display_title': 'Metamorphosis Aesthetic Pvt. Ltd. — Greater kailash'}, 'count': 30, 'sum_net_amount': 454496}, 'data': [{'billing_transaction_id': 56652, 'billing_id': 59059, 'invoice_no': 'MC/GK/2627862', 'receipt_no': 'MC/GK/2627862-RECB2189025', 'payment_date': '2026-04-30 16:23:10', 'package_name': 'Balance of full body LHR', 'sale': {'amount': 20000, 'tax_amount': 1000, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 21000, 'taxable_value': 20000, 'total_invoice_value': 21000}, 'payment': {'mode_of_payment': 'UPI', 'modes_from_logs': 'UPI'}, 'patient': {'patient_id': 31631, 'patient_name': 'kriti wadhwa', 'mobile_no': '8130506307'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56624, 'billing_id': 60177, 'invoice_no': 'MC/GK/2627861', 'receipt_no': 'MC/GK/2627861-RECA66C0ABC', 'payment_date': '2026-04-29 18:41:14', 'package_name': 'chin', 'sale': {'amount': 6666, 'tax_amount': 333.33, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 7000, 'taxable_value': 6666.67, 'total_invoice_value': 7000}, 'payment': {'mode_of_payment': 'UPI', 'modes_from_logs': 'UPI'}, 'patient': {'patient_id': 32209, 'patient_name': 'jyoti .', 'mobile_no': '9315789446'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56560, 'billing_id': 60097, 'invoice_no': 'MC/GK/2627860', 'receipt_no': 'MC/GK/2627860-REC3EC65D60', 'payment_date': '2026-04-27 11:53:50', 'package_name': 'LOWER FACE LHR', 'sale': {'amount': 952, 'tax_amount': 47.62, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 1000, 'taxable_value': 952.38, 'total_invoice_value': 1000}, 'payment': {'mode_of_payment': 'CASH', 'modes_from_logs': 'CASH'}, 'patient': {'patient_id': 26463, 'patient_name': 'Priyanka Choudhary', 'mobile_no': '8810256653'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56504, 'billing_id': 60038, 'invoice_no': 'MC/GK/2627858', 'receipt_no': 'MC/GK/2627858-REC46283C9A', 'payment_date': '2026-04-26 11:38:10', 'package_name': 'full face', 'sale': {'amount': 7142, 'tax_amount': 357.14, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 7500, 'taxable_value': 7142.86, 'total_invoice_value': 7500}, 'payment': {'mode_of_payment': 'DEBIT_CARD', 'modes_from_logs': 'DEBIT_CARD'}, 'patient': {'patient_id': 32150, 'patient_name': 'aastha kukreja', 'mobile_no': '9315507183'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56475, 'billing_id': 60009, 'invoice_no': 'MC/GK/2627856', 'receipt_no': 'MC/GK/2627856-RECD248663E', 'payment_date': '2026-04-25 17:43:31', 'package_name': 'full face', 'sale': {'amount': 18000, 'tax_amount': 900, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 18900, 'taxable_value': 18000, 'total_invoice_value': 18900}, 'payment': {'mode_of_payment': 'UPI', 'modes_from_logs': 'UPI'}, 'patient': {'patient_id': 26331, 'patient_name': 'Ishita Minocha', 'mobile_no': '9833228529'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56467, 'billing_id': 59999, 'invoice_no': 'MC/GK/2627854', 'receipt_no': 'MC/GK/2627854-REC26BEE42A', 'payment_date': '2026-04-25 16:37:29', 'package_name': 'full body LHR', 'sale': {'amount': 43809, 'tax_amount': 2190.48, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 46000, 'taxable_value': 43809.52, 'total_invoice_value': 46000}, 'payment': {'mode_of_payment': 'UPI', 'modes_from_logs': 'UPI'}, 'patient': {'patient_id': 26610, 'patient_name': 'TEENA CHANDRA', 'mobile_no': '8758704968'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56465, 'billing_id': 59994, 'invoice_no': 'MC/GK/2627852', 'receipt_no': 'MC/GK/2627852-RECA1045779', 'payment_date': '2026-04-25 14:25:21', 'package_name': 'chin, upperlips, neck', 'sale': {'amount': 1904, 'tax_amount': 95.24, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 2000, 'taxable_value': 1904.76, 'total_invoice_value': 2000}, 'payment': {'mode_of_payment': 'UPI', 'modes_from_logs': 'UPI'}, 'patient': {'patient_id': 32117, 'patient_name': 'ayushi kashap', 'mobile_no': '9667219309'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56440, 'billing_id': 59964, 'invoice_no': 'MC/GK/2627850', 'receipt_no': 'MC/GK/2627850-REC6A1B581A', 'payment_date': '2026-04-24 15:39:32', 'package_name': 'full body LHR', 'sale': {'amount': 19047, 'tax_amount': 952.38, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 20000, 'taxable_value': 19047.62, 'total_invoice_value': 20000}, 'payment': {'mode_of_payment': 'CASH', 'modes_from_logs': 'CASH'}, 'patient': {'patient_id': 32094, 'patient_name': 'dolly nagpal', 'mobile_no': '9619614239'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56428, 'billing_id': 59943, 'invoice_no': 'MC/GK/2627848', 'receipt_no': 'MC/GK/2627848-RECBB0B4745', 'payment_date': '2026-04-24 12:46:07', 'package_name': 'HYDRAFACIAL', 'sale': {'amount': 3809, 'tax_amount': 190.48, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 4000, 'taxable_value': 3809.52, 'total_invoice_value': 4000}, 'payment': {'mode_of_payment': 'DEBIT_CARD', 'modes_from_logs': 'DEBIT_CARD'}, 'patient': {'patient_id': 32081, 'patient_name': 'sahhej anand', 'mobile_no': '8800495717'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56403, 'billing_id': 59917, 'invoice_no': 'MC/GK/2627847', 'receipt_no': 'MC/GK/2627847-REC1D27F96A', 'payment_date': '2026-04-23 15:34:52', 'package_name': 'LOWER FACE LHR', 'sale': {'amount': 2380, 'tax_amount': 119.05, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 2500, 'taxable_value': 2380.95, 'total_invoice_value': 2500}, 'payment': {'mode_of_payment': 'UPI', 'modes_from_logs': 'UPI'}, 'patient': {'patient_id': 32059, 'patient_name': 'shradha sharma', 'mobile_no': '9131543148'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56401, 'billing_id': 59914, 'invoice_no': 'MC/GK/2627845', 'receipt_no': 'MC/GK/2627845-REC1E683914', 'payment_date': '2026-04-23 15:13:47', 'package_name': 'full body LHR', 'sale': {'amount': 40238, 'tax_amount': 2011.9, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 42250, 'taxable_value': 40238.1, 'total_invoice_value': 42250}, 'payment': {'mode_of_payment': 'UPI', 'modes_from_logs': 'UPI'}, 'patient': {'patient_id': 32064, 'patient_name': 'Anu kathuria', 'mobile_no': '9891420360'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56378, 'billing_id': 59822, 'invoice_no': 'MC/GK/2627843', 'receipt_no': 'MC/GK/2627843-RECE92DE350', 'payment_date': '2026-04-22 15:37:48', 'package_name': 'Balance of full body LHR', 'sale': {'amount': 40238, 'tax_amount': 2011.9, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 42250, 'taxable_value': 40238.1, 'total_invoice_value': 42250}, 'payment': {'mode_of_payment': 'CASH', 'modes_from_logs': 'CASH'}, 'patient': {'patient_id': 32016, 'patient_name': 'anukriti gambhir', 'mobile_no': '9855483064'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56373, 'billing_id': 59872, 'invoice_no': 'MC/GK/2627842', 'receipt_no': 'MC/GK/2627842-RECE97A5605', 'payment_date': '2026-04-22 12:21:21', 'package_name': 'full body LHR', 'sale': {'amount': 16666, 'tax_amount': 833.33, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 17500, 'taxable_value': 16666.67, 'total_invoice_value': 17500}, 'payment': {'mode_of_payment': 'UPI', 'modes_from_logs': 'UPI'}, 'patient': {'patient_id': 27762, 'patient_name': 'Priya Chandna', 'mobile_no': '8826871833'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56336, 'billing_id': 59822, 'invoice_no': 'MC/GK/2627841', 'receipt_no': 'MC/GK/2627841-RECB3A6B15B', 'payment_date': '2026-04-20 15:18:57', 'package_name': 'full body LHR', 'sale': {'amount': 4761, 'tax_amount': 238.1, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 5000, 'taxable_value': 4761.9, 'total_invoice_value': 5000}, 'payment': {'mode_of_payment': 'CASH', 'modes_from_logs': 'CASH'}, 'patient': {'patient_id': 32016, 'patient_name': 'anukriti gambhir', 'mobile_no': '9855483064'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56280, 'billing_id': 59745, 'invoice_no': 'MC/GK/2627836', 'receipt_no': 'MC/GK/2627836-REC30870DEF', 'payment_date': '2026-04-18 17:39:24', 'package_name': 'hydrafacial', 'sale': {'amount': 4761, 'tax_amount': 238.1, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 5000, 'taxable_value': 4761.9, 'total_invoice_value': 5000}, 'payment': {'mode_of_payment': 'CASH', 'modes_from_logs': 'CASH'}, 'patient': {'patient_id': 31968, 'patient_name': 'AKSHITA .', 'mobile_no': '9711004423'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56278, 'billing_id': 59743, 'invoice_no': 'MC/GK/2627835', 'receipt_no': 'MC/GK/2627835-RECA4B8D572', 'payment_date': '2026-04-18 17:35:21', 'package_name': 'LOWER FACE LHR', 'sale': {'amount': 7142, 'tax_amount': 357.14, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 7500, 'taxable_value': 7142.86, 'total_invoice_value': 7500}, 'payment': {'mode_of_payment': 'CASH', 'modes_from_logs': 'CASH'}, 'patient': {'patient_id': 26351, 'patient_name': 'Kamlesh', 'mobile_no': '7015701627'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56269, 'billing_id': 59726, 'invoice_no': 'MC/GK/2627833', 'receipt_no': 'MC/GK/2627833-REC5F17798F', 'payment_date': '2026-04-18 13:35:10', 'package_name': 'kenacort injection', 'sale': {'amount': 2380, 'tax_amount': 119.05, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 2500, 'taxable_value': 2380.95, 'total_invoice_value': 2500}, 'payment': {'mode_of_payment': 'UPI', 'modes_from_logs': 'UPI'}, 'patient': {'patient_id': 27362, 'patient_name': 'JYOTSANA  SINGH', 'mobile_no': '8595219006'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56253, 'billing_id': 59707, 'invoice_no': 'MC/GK/2627832', 'receipt_no': 'MC/GK/2627832-RECEE7FEB51', 'payment_date': '2026-04-17 19:15:26', 'package_name': 'full body LHR', 'sale': {'amount': 7619, 'tax_amount': 380.95, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 8000, 'taxable_value': 7619.05, 'total_invoice_value': 8000}, 'payment': {'mode_of_payment': 'UPI', 'modes_from_logs': 'UPI'}, 'patient': {'patient_id': 26239, 'patient_name': 'ANU GUPTA', 'mobile_no': '9625048534'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56247, 'billing_id': 59692, 'invoice_no': 'MC/GK/2627830', 'receipt_no': 'MC/GK/2627830-RECB0969896', 'payment_date': '2026-04-17 16:30:55', 'package_name': 'underarms, half legs', 'sale': {'amount': 4666, 'tax_amount': 233.33, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 4900, 'taxable_value': 4666.67, 'total_invoice_value': 4900}, 'payment': {'mode_of_payment': 'DEBIT_CARD', 'modes_from_logs': 'DEBIT_CARD'}, 'patient': {'patient_id': 27795, 'patient_name': 'pathrese  abuela', 'mobile_no': '9181114558'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56151, 'billing_id': 59565, 'invoice_no': 'MC/PO/2627287', 'receipt_no': 'MC/PO/2627287-REC61566029', 'payment_date': '2026-04-13 19:32:12', 'package_name': 'full body LHR', 'sale': {'amount': 9523, 'tax_amount': 476.19, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 10000, 'taxable_value': 9523.81, 'total_invoice_value': 10000}, 'payment': {'mode_of_payment': 'UPI', 'modes_from_logs': 'UPI'}, 'patient': {'patient_id': 1600, 'patient_name': 'Puja Jaiswal', 'mobile_no': '917349491146'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56109, 'billing_id': 59517, 'invoice_no': 'MC/GK/2627824', 'receipt_no': 'MC/GK/2627824-REC41A387A8', 'payment_date': '2026-04-13 12:11:19', 'package_name': 'full body LHR', 'sale': {'amount': 26190, 'tax_amount': 1309.52, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 27500, 'taxable_value': 26190.48, 'total_invoice_value': 27500}, 'payment': {'mode_of_payment': 'UPI', 'modes_from_logs': 'UPI'}, 'patient': {'patient_id': 31838, 'patient_name': 'pranchal chauhan', 'mobile_no': '9319717914'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56077, 'billing_id': 59460, 'invoice_no': 'MC/GK/2627820', 'receipt_no': 'MC/GK/2627820-REC398EA2D2', 'payment_date': '2026-04-12 13:49:03', 'package_name': '1 hydrafacial and 2 Rf facial', 'sale': {'amount': 12857, 'tax_amount': 642.86, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 13500, 'taxable_value': 12857.14, 'total_invoice_value': 13500}, 'payment': {'mode_of_payment': 'CREDIT_CARD', 'modes_from_logs': 'CREDIT_CARD'}, 'patient': {'patient_id': 26322, 'patient_name': 'harneet bedi', 'mobile_no': '9818096200'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56051, 'billing_id': 59427, 'invoice_no': 'MC/GK/2627816', 'receipt_no': 'MC/GK/2627816-REC28C0A45F', 'payment_date': '2026-04-11 16:32:39', 'package_name': 'full body LHR', 'sale': {'amount': 45000, 'tax_amount': 2250, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 47250, 'taxable_value': 45000, 'total_invoice_value': 47250}, 'payment': {'mode_of_payment': 'UPI', 'modes_from_logs': 'UPI'}, 'patient': {'patient_id': 31802, 'patient_name': 'anushka singh', 'mobile_no': '9179930409'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 56044, 'billing_id': 59270, 'invoice_no': 'MC/GK/2627815', 'receipt_no': 'MC/GK/2627815-REC23CCFEFC', 'payment_date': '2026-04-11 15:59:46', 'package_name': 'Balance of full body LHR', 'sale': {'amount': 5043, 'tax_amount': 252.19, 'tax_percent': '5.00', 'discount_amount': '0.00', 'net_amount': 5296, 'taxable_value': 5043.81, 'total_invoice_value': 5296}, 'payment': {'mode_of_payment': 'UPI', 'modes_from_logs': 'UPI'}, 'patient': {'patient_id': 31730, 'patient_name': 'zoha khan', 'mobile_no': '9675073544'}, 'staff': {'id': 53, 'staff_name': 'Hina Kausar', 'mobile': '8383844224'}, 'remarks': 'Multiple payment transaction', 'status': 'success', 'transaction_type': 'payment', 'source': 'staging', 'cancellation': {'is_cancel': False, 'cancel_date': None, 'cancel_remark': None}}, {'billing_transaction_id': 55932, 'billing_id': 59270, 'invoice_no': 'MC/G

C:\Users\ayush\AppData\Local\Temp\ipykernel_17388\797199553.py:22: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.select_dtypes(include="object").columns)

In [6]:
df = pd.DataFrame(data["data"])
df

,billing_transaction_id,billing_id,invoice_no,receipt_no,payment_date,package_name,sale,payment,patient,staff,remarks,status,transaction_type,source,cancellation
0,56652,59059,MC/GK/2627862,MC/GK/2627862-RECB2189025,2026-04-30 16:23:10,Balance of full body LHR,"{'amount': 20000, 'tax_amount': 1000, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 31631, 'patient_name': 'kriti w...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
1,56624,60177,MC/GK/2627861,MC/GK/2627861-RECA66C0ABC,2026-04-29 18:41:14,chin,"{'amount': 6666, 'tax_amount': 333.33, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 32209, 'patient_name': 'jyoti ....","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
2,56560,60097,MC/GK/2627860,MC/GK/2627860-REC3EC65D60,2026-04-27 11:53:50,LOWER FACE LHR,"{'amount': 952, 'tax_amount': 47.62, 'tax_perc...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 26463, 'patient_name': 'Priyank...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
3,56504,60038,MC/GK/2627858,MC/GK/2627858-REC46283C9A,2026-04-26 11:38:10,full face,"{'amount': 7142, 'tax_amount': 357.14, 'tax_pe...","{'mode_of_payment': 'DEBIT_CARD', 'modes_from_...","{'patient_id': 32150, 'patient_name': 'aastha ...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
4,56475,60009,MC/GK/2627856,MC/GK/2627856-RECD248663E,2026-04-25 17:43:31,full face,"{'amount': 18000, 'tax_amount': 900, 'tax_perc...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 26331, 'patient_name': 'Ishita ...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
5,56467,59999,MC/GK/2627854,MC/GK/2627854-REC26BEE42A,2026-04-25 16:37:29,full body LHR,"{'amount': 43809, 'tax_amount': 2190.48, 'tax_...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 26610, 'patient_name': 'TEENA C...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
6,56465,59994,MC/GK/2627852,MC/GK/2627852-RECA1045779,2026-04-25 14:25:21,"chin, upperlips, neck","{'amount': 1904, 'tax_amount': 95.24, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 32117, 'patient_name': 'ayushi ...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
7,56440,59964,MC/GK/2627850,MC/GK/2627850-REC6A1B581A,2026-04-24 15:39:32,full body LHR,"{'amount': 19047, 'tax_amount': 952.38, 'tax_p...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 32094, 'patient_name': 'dolly n...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
8,56428,59943,MC/GK/2627848,MC/GK/2627848-RECBB0B4745,2026-04-24 12:46:07,HYDRAFACIAL,"{'amount': 3809, 'tax_amount': 190.48, 'tax_pe...","{'mode_of_payment': 'DEBIT_CARD', 'modes_from_...","{'patient_id': 32081, 'patient_name': 'sahhej ...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
9,56403,59917,MC/GK/2627847,MC/GK/2627847-REC1D27F96A,2026-04-23 15:34:52,LOWER FACE LHR,"{'amount': 2380, 'tax_amount': 119.05, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 32059, 'patient_name': 'shradha...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
10,56401,59914,MC/GK/2627845,MC/GK/2627845-REC1E683914,2026-04-23 15:13:47,full body LHR,"{'amount': 40238, 'tax_amount': 2011.9, 'tax_p...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 32064, 'patient_name': 'Anu kat...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
11,56378,59822,MC/GK/2627843,MC/GK/2627843-RECE92DE350,2026-04-22 15:37:48,Balance of full body LHR,"{'amount': 40238, 'tax_amount': 2011.9, 'tax_p...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 32016, 'patient_name': 'anukrit...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
12,56373,59872,MC/GK/2627842,MC/GK/2627842-RECE97A5605,2026-04-22 12:21:21,full body LHR,"{'amount': 16666, 'tax_amount': 833.33, 'tax_p...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 27762, 'patient_name': 'Priya C...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
13,56336,59822,MC/GK/2627841,MC/GK/2627841-RECB3A6B15B,2026-04-20 15:18:57,full body LHR,"{'amount': 4761, 'tax_amount': 238.1, 'tax_per...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 32016, 'patient_name': 'anukrit...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
14,56280,59745,MC/GK/2627836,MC/GK/2627836-REC30870DEF,2026-04-18 17:39:24,hydrafacial,"{'amount': 4761, 'tax_amount': 238.1, 'tax_per...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 31968, 'patient_name': 'AKSHITA...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
15,56278,59743,MC/GK/2627835,MC/GK/2627835-RECA4B8D572,2026-04-18 17:35:21,LOWER FACE LHR,"{'amount': 7142, 'tax_amount': 357.14, 'tax_pe...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 26351, 'patient_name': 'Kamlesh...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
16,56269,59726,MC/GK/2627833,MC/GK/2627833-REC5F17798F,2026-04-18 13:35:10,kenacort injection,"{'amount': 2380, 'tax_amount': 119.05, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 27362, 'patient_name': 'JYOTSAN...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
17,56253,59707,MC/GK/2627832,MC/GK/2627832-RECEE7FEB51,2026-04-17 19:15:26,full body LHR,"{'amount': 7619, 'tax_amount': 380.95, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 26239, 'patient_name': 'ANU GUP...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
18,56247,59692,MC/GK/2627830,MC/GK/2627830-RECB0969896,2026-04-17 16:30:55,"underarms, half legs","{'amount': 4666, 'tax_amount': 233.33, 'tax_pe...","{'mode_of_payment': 'DEBIT_CARD', 'modes_from_...","{'patient_id': 27795, 'patient_name': 'pathres...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
19,56151,59565,MC/PO/2627287,MC/PO/2627287-REC61566029,2026-04-13 19:32:12,full body LHR,"{'amount': 9523, 'tax_amount': 476.19, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 1600, 'patient_name': 'Puja Jai...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
20,56109,59517,MC/GK/2627824,MC/GK/2627824-REC41A387A8,2026-04-13 12:11:19,full body LHR,"{'amount': 26190, 'tax_amount': 1309.52, 'tax_...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 31838, 'patient_name': 'prancha...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
21,56077,59460,MC/GK/2627820,MC/GK/2627820-REC398EA2D2,2026-04-12 13:49:03,1 hydrafacial and 2 Rf facial,"{'amount': 12857, 'tax_amount': 642.86, 'tax_p...","{'mode_of_payment': 'CREDIT_CARD', 'modes_from...","{'patient_id': 26322, 'patient_name': 'harneet...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
22,56051,59427,MC/GK/2627816,MC/GK/2627816-REC28C0A45F,2026-04-11 16:32:39,full body LHR,"{'amount': 45000, 'tax_amount': 2250, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 31802, 'patient_name': 'anushka...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
23,56044,59270,MC/GK/2627815,MC/GK/2627815-REC23CCFEFC,2026-04-11 15:59:46,Balance of full body LHR,"{'amount': 5043, 'tax_amount': 252.19, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 31730, 'patient_name': 'zoha kh...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
24,55932,59270,MC/GK/2627810,MC/GK/2627810-RECE7F8D6E3,2026-04-08 18:23:37,full body LHR,"{'amount': 45000, 'tax_amount': 2250, 'tax_per...","{'mode_of_payment': 'SAVEIN', 'modes_from_logs...","{'patient_id': 31730, 'patient_name': 'zoha kh...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
25,55927,59256,MC/GK/2627808,MC/GK/2627808-REC7D4A28FA,2026-04-08 16:28:52,"bodypolishing, hydrafacial","{'amount': 4761, 'tax_amount': 238.1, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 26241, 'patient_name': 'Anupama...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
26,55926,59059,MC/GK/2627807,MC/GK/2627807-REC11118C49,2026-04-08 16:10:06,Balance of full body LHR,"{'amount': 20000, 'tax_amount': 1000, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 31631, 'patient_name': 'kriti w...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
27,55773,59059,MC/GK/2627803,MC/GK/2627803-REC10DBA501,2026-04-03 17:12:03,full body LHR,"{'amount': 5714, 'tax_amount': 285.71, 'tax_pe...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 31631, 'patient_name': 'kriti w...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
28,55627,58643,MC/GK/2627802,MC/GK/2627802-RECBD2E6A15,2026-04-02 17:02:42,"UNDERARMS, HALF LEGS","{'amount': 4666, 'tax_amount': 233.33, 'tax_pe...","{'mode_of_payment': 'DEBIT_CARD', 'modes_from_...","{'patient_id': 27795, 'patient_name': 'pathres...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
29,53055,55287,MC/GK/2627801,MC/GK/2627801-REC3E3EB7DE,2026-04-01 17:39:52,full face,"{'amount': 1904, 'tax_amount': 95.24, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 27350, 'patient_name': 'TASREEN...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."

In [7]:
df = pd.json_normalize(data)
df

,success,source,data,meta.user_map_id,meta.start_date,meta.end_date,meta.payment_range.gte,meta.payment_range.lt,meta.location.user_map_id,meta.location.clinic_name,meta.location.city,meta.location.display_title,meta.count,meta.sum_net_amount
0,True,docexa_billing_only,"[{'billing_transaction_id': 56652, 'billing_id...",70697,2026-04-01,2026-04-30,2026-04-01 00:00:00,2026-05-01 00:00:00,70697,Metamorphosis Aesthetic Pvt. Ltd.,Greater kailash,Metamorphosis Aesthetic Pvt. Ltd. — Greater ka...,30,454496

In [8]:
df.head()

,success,source,data,meta.user_map_id,meta.start_date,meta.end_date,meta.payment_range.gte,meta.payment_range.lt,meta.location.user_map_id,meta.location.clinic_name,meta.location.city,meta.location.display_title,meta.count,meta.sum_net_amount
0,True,docexa_billing_only,"[{'billing_transaction_id': 56652, 'billing_id...",70697,2026-04-01,2026-04-30,2026-04-01 00:00:00,2026-05-01 00:00:00,70697,Metamorphosis Aesthetic Pvt. Ltd.,Greater kailash,Metamorphosis Aesthetic Pvt. Ltd. — Greater ka...,30,454496

In [9]:
df.isnull().sum()

success                        0
source                         0
data                           0
meta.user_map_id               0
meta.start_date                0
meta.end_date                  0
meta.payment_range.gte         0
meta.payment_range.lt          0
meta.location.user_map_id      0
meta.location.clinic_name      0
meta.location.city             0
meta.location.display_title    0
meta.count                     0
meta.sum_net_amount            0
dtype: int64

In [10]:
df.select_dtypes(include="object").columns

C:\Users\ayush\AppData\Local\Temp\ipykernel_17388\1196084386.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").columns

Index(['source', 'data', 'meta.start_date', 'meta.end_date',
       'meta.payment_range.gte', 'meta.payment_range.lt',
       'meta.location.clinic_name', 'meta.location.city',
       'meta.location.display_title'],
      dtype='str')

In [11]:
df.columns

Index(['success', 'source', 'data', 'meta.user_map_id', 'meta.start_date',
       'meta.end_date', 'meta.payment_range.gte', 'meta.payment_range.lt',
       'meta.location.user_map_id', 'meta.location.clinic_name',
       'meta.location.city', 'meta.location.display_title', 'meta.count',
       'meta.sum_net_amount'],
      dtype='str')

TypeError: 'Index' object is not callable