In [23]:
import requests
import pandas as pd


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

from xgboost import XGBClassifier

In [24]:
url = "https://metamorphosis.youv.ai/api/billing/sales-period?user_map_id=70697&start_date=2026-04-01&end_date=2026-04-30"

In [25]:
params= {
    "user_map_id": 70697,
    "start_date": "2026-04-01",
    "end_date: ": "2026-04-30"
    }

response = requests.get(url, params = params)
data = response.json()

In [26]:
df = pd.DataFrame(data["data"])
df

,billing_transaction_id,billing_id,invoice_no,receipt_no,payment_date,package_name,sale,payment,patient,staff,remarks,status,transaction_type,source,cancellation
0,56652,59059,MC/GK/2627862,MC/GK/2627862-RECB2189025,2026-04-30 16:23:10,Balance of full body LHR,"{'amount': 20000, 'tax_amount': 1000, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 31631, 'patient_name': 'kriti w...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
1,56624,60177,MC/GK/2627861,MC/GK/2627861-RECA66C0ABC,2026-04-29 18:41:14,chin,"{'amount': 6666, 'tax_amount': 333.33, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 32209, 'patient_name': 'jyoti ....","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
2,56560,60097,MC/GK/2627860,MC/GK/2627860-REC3EC65D60,2026-04-27 11:53:50,LOWER FACE LHR,"{'amount': 952, 'tax_amount': 47.62, 'tax_perc...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 26463, 'patient_name': 'Priyank...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
3,56504,60038,MC/GK/2627858,MC/GK/2627858-REC46283C9A,2026-04-26 11:38:10,full face,"{'amount': 7142, 'tax_amount': 357.14, 'tax_pe...","{'mode_of_payment': 'DEBIT_CARD', 'modes_from_...","{'patient_id': 32150, 'patient_name': 'aastha ...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
4,56475,60009,MC/GK/2627856,MC/GK/2627856-RECD248663E,2026-04-25 17:43:31,full face,"{'amount': 18000, 'tax_amount': 900, 'tax_perc...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 26331, 'patient_name': 'Ishita ...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
5,56467,59999,MC/GK/2627854,MC/GK/2627854-REC26BEE42A,2026-04-25 16:37:29,full body LHR,"{'amount': 43809, 'tax_amount': 2190.48, 'tax_...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 26610, 'patient_name': 'TEENA C...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
6,56465,59994,MC/GK/2627852,MC/GK/2627852-RECA1045779,2026-04-25 14:25:21,"chin, upperlips, neck","{'amount': 1904, 'tax_amount': 95.24, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 32117, 'patient_name': 'ayushi ...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
7,56440,59964,MC/GK/2627850,MC/GK/2627850-REC6A1B581A,2026-04-24 15:39:32,full body LHR,"{'amount': 19047, 'tax_amount': 952.38, 'tax_p...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 32094, 'patient_name': 'dolly n...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
8,56428,59943,MC/GK/2627848,MC/GK/2627848-RECBB0B4745,2026-04-24 12:46:07,HYDRAFACIAL,"{'amount': 3809, 'tax_amount': 190.48, 'tax_pe...","{'mode_of_payment': 'DEBIT_CARD', 'modes_from_...","{'patient_id': 32081, 'patient_name': 'sahhej ...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
9,56403,59917,MC/GK/2627847,MC/GK/2627847-REC1D27F96A,2026-04-23 15:34:52,LOWER FACE LHR,"{'amount': 2380, 'tax_amount': 119.05, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 32059, 'patient_name': 'shradha...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
10,56401,59914,MC/GK/2627845,MC/GK/2627845-REC1E683914,2026-04-23 15:13:47,full body LHR,"{'amount': 40238, 'tax_amount': 2011.9, 'tax_p...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 32064, 'patient_name': 'Anu kat...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
11,56378,59822,MC/GK/2627843,MC/GK/2627843-RECE92DE350,2026-04-22 15:37:48,Balance of full body LHR,"{'amount': 40238, 'tax_amount': 2011.9, 'tax_p...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 32016, 'patient_name': 'anukrit...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
12,56373,59872,MC/GK/2627842,MC/GK/2627842-RECE97A5605,2026-04-22 12:21:21,full body LHR,"{'amount': 16666, 'tax_amount': 833.33, 'tax_p...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 27762, 'patient_name': 'Priya C...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
13,56336,59822,MC/GK/2627841,MC/GK/2627841-RECB3A6B15B,2026-04-20 15:18:57,full body LHR,"{'amount': 4761, 'tax_amount': 238.1, 'tax_per...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 32016, 'patient_name': 'anukrit...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
14,56280,59745,MC/GK/2627836,MC/GK/2627836-REC30870DEF,2026-04-18 17:39:24,hydrafacial,"{'amount': 4761, 'tax_amount': 238.1, 'tax_per...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 31968, 'patient_name': 'AKSHITA...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
15,56278,59743,MC/GK/2627835,MC/GK/2627835-RECA4B8D572,2026-04-18 17:35:21,LOWER FACE LHR,"{'amount': 7142, 'tax_amount': 357.14, 'tax_pe...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 26351, 'patient_name': 'Kamlesh...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
16,56269,59726,MC/GK/2627833,MC/GK/2627833-REC5F17798F,2026-04-18 13:35:10,kenacort injection,"{'amount': 2380, 'tax_amount': 119.05, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 27362, 'patient_name': 'JYOTSAN...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
17,56253,59707,MC/GK/2627832,MC/GK/2627832-RECEE7FEB51,2026-04-17 19:15:26,full body LHR,"{'amount': 7619, 'tax_amount': 380.95, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 26239, 'patient_name': 'ANU GUP...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
18,56247,59692,MC/GK/2627830,MC/GK/2627830-RECB0969896,2026-04-17 16:30:55,"underarms, half legs","{'amount': 4666, 'tax_amount': 233.33, 'tax_pe...","{'mode_of_payment': 'DEBIT_CARD', 'modes_from_...","{'patient_id': 27795, 'patient_name': 'pathres...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
19,56151,59565,MC/PO/2627287,MC/PO/2627287-REC61566029,2026-04-13 19:32:12,full body LHR,"{'amount': 9523, 'tax_amount': 476.19, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 1600, 'patient_name': 'Puja Jai...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
20,56109,59517,MC/GK/2627824,MC/GK/2627824-REC41A387A8,2026-04-13 12:11:19,full body LHR,"{'amount': 26190, 'tax_amount': 1309.52, 'tax_...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 31838, 'patient_name': 'prancha...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
21,56077,59460,MC/GK/2627820,MC/GK/2627820-REC398EA2D2,2026-04-12 13:49:03,1 hydrafacial and 2 Rf facial,"{'amount': 12857, 'tax_amount': 642.86, 'tax_p...","{'mode_of_payment': 'CREDIT_CARD', 'modes_from...","{'patient_id': 26322, 'patient_name': 'harneet...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
22,56051,59427,MC/GK/2627816,MC/GK/2627816-REC28C0A45F,2026-04-11 16:32:39,full body LHR,"{'amount': 45000, 'tax_amount': 2250, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 31802, 'patient_name': 'anushka...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
23,56044,59270,MC/GK/2627815,MC/GK/2627815-REC23CCFEFC,2026-04-11 15:59:46,Balance of full body LHR,"{'amount': 5043, 'tax_amount': 252.19, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 31730, 'patient_name': 'zoha kh...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
24,55932,59270,MC/GK/2627810,MC/GK/2627810-RECE7F8D6E3,2026-04-08 18:23:37,full body LHR,"{'amount': 45000, 'tax_amount': 2250, 'tax_per...","{'mode_of_payment': 'SAVEIN', 'modes_from_logs...","{'patient_id': 31730, 'patient_name': 'zoha kh...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
25,55927,59256,MC/GK/2627808,MC/GK/2627808-REC7D4A28FA,2026-04-08 16:28:52,"bodypolishing, hydrafacial","{'amount': 4761, 'tax_amount': 238.1, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 26241, 'patient_name': 'Anupama...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
26,55926,59059,MC/GK/2627807,MC/GK/2627807-REC11118C49,2026-04-08 16:10:06,Balance of full body LHR,"{'amount': 20000, 'tax_amount': 1000, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 31631, 'patient_name': 'kriti w...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
27,55773,59059,MC/GK/2627803,MC/GK/2627803-REC10DBA501,2026-04-03 17:12:03,full body LHR,"{'amount': 5714, 'tax_amount': 285.71, 'tax_pe...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 31631, 'patient_name': 'kriti w...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
28,55627,58643,MC/GK/2627802,MC/GK/2627802-RECBD2E6A15,2026-04-02 17:02:42,"UNDERARMS, HALF LEGS","{'amount': 4666, 'tax_amount': 233.33, 'tax_pe...","{'mode_of_payment': 'DEBIT_CARD', 'modes_from_...","{'patient_id': 27795, 'patient_name': 'pathres...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
29,53055,55287,MC/GK/2627801,MC/GK/2627801-REC3E3EB7DE,2026-04-01 17:39:52,full face,"{'amount': 1904, 'tax_amount': 95.24, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 27350, 'patient_name': 'TASREEN...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",Multiple payment transaction,success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."

In [27]:
df.columns

Index(['billing_transaction_id', 'billing_id', 'invoice_no', 'receipt_no',
       'payment_date', 'package_name', 'sale', 'payment', 'patient', 'staff',
       'remarks', 'status', 'transaction_type', 'source', 'cancellation'],
      dtype='str')

In [28]:
df = df.drop(columns=[
    'billing_transaction_id',
    'billing_id',
    'invoice_no',
    'receipt_no',
    'remarks'
])
df

,payment_date,package_name,sale,payment,patient,staff,status,transaction_type,source,cancellation
0,2026-04-30 16:23:10,Balance of full body LHR,"{'amount': 20000, 'tax_amount': 1000, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 31631, 'patient_name': 'kriti w...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
1,2026-04-29 18:41:14,chin,"{'amount': 6666, 'tax_amount': 333.33, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 32209, 'patient_name': 'jyoti ....","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
2,2026-04-27 11:53:50,LOWER FACE LHR,"{'amount': 952, 'tax_amount': 47.62, 'tax_perc...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 26463, 'patient_name': 'Priyank...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
3,2026-04-26 11:38:10,full face,"{'amount': 7142, 'tax_amount': 357.14, 'tax_pe...","{'mode_of_payment': 'DEBIT_CARD', 'modes_from_...","{'patient_id': 32150, 'patient_name': 'aastha ...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
4,2026-04-25 17:43:31,full face,"{'amount': 18000, 'tax_amount': 900, 'tax_perc...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 26331, 'patient_name': 'Ishita ...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
5,2026-04-25 16:37:29,full body LHR,"{'amount': 43809, 'tax_amount': 2190.48, 'tax_...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 26610, 'patient_name': 'TEENA C...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
6,2026-04-25 14:25:21,"chin, upperlips, neck","{'amount': 1904, 'tax_amount': 95.24, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 32117, 'patient_name': 'ayushi ...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
7,2026-04-24 15:39:32,full body LHR,"{'amount': 19047, 'tax_amount': 952.38, 'tax_p...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 32094, 'patient_name': 'dolly n...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
8,2026-04-24 12:46:07,HYDRAFACIAL,"{'amount': 3809, 'tax_amount': 190.48, 'tax_pe...","{'mode_of_payment': 'DEBIT_CARD', 'modes_from_...","{'patient_id': 32081, 'patient_name': 'sahhej ...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
9,2026-04-23 15:34:52,LOWER FACE LHR,"{'amount': 2380, 'tax_amount': 119.05, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 32059, 'patient_name': 'shradha...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
10,2026-04-23 15:13:47,full body LHR,"{'amount': 40238, 'tax_amount': 2011.9, 'tax_p...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 32064, 'patient_name': 'Anu kat...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
11,2026-04-22 15:37:48,Balance of full body LHR,"{'amount': 40238, 'tax_amount': 2011.9, 'tax_p...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 32016, 'patient_name': 'anukrit...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
12,2026-04-22 12:21:21,full body LHR,"{'amount': 16666, 'tax_amount': 833.33, 'tax_p...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 27762, 'patient_name': 'Priya C...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
13,2026-04-20 15:18:57,full body LHR,"{'amount': 4761, 'tax_amount': 238.1, 'tax_per...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 32016, 'patient_name': 'anukrit...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
14,2026-04-18 17:39:24,hydrafacial,"{'amount': 4761, 'tax_amount': 238.1, 'tax_per...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 31968, 'patient_name': 'AKSHITA...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
15,2026-04-18 17:35:21,LOWER FACE LHR,"{'amount': 7142, 'tax_amount': 357.14, 'tax_pe...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 26351, 'patient_name': 'Kamlesh...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
16,2026-04-18 13:35:10,kenacort injection,"{'amount': 2380, 'tax_amount': 119.05, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 27362, 'patient_name': 'JYOTSAN...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
17,2026-04-17 19:15:26,full body LHR,"{'amount': 7619, 'tax_amount': 380.95, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 26239, 'patient_name': 'ANU GUP...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
18,2026-04-17 16:30:55,"underarms, half legs","{'amount': 4666, 'tax_amount': 233.33, 'tax_pe...","{'mode_of_payment': 'DEBIT_CARD', 'modes_from_...","{'patient_id': 27795, 'patient_name': 'pathres...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
19,2026-04-13 19:32:12,full body LHR,"{'amount': 9523, 'tax_amount': 476.19, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 1600, 'patient_name': 'Puja Jai...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
20,2026-04-13 12:11:19,full body LHR,"{'amount': 26190, 'tax_amount': 1309.52, 'tax_...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 31838, 'patient_name': 'prancha...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
21,2026-04-12 13:49:03,1 hydrafacial and 2 Rf facial,"{'amount': 12857, 'tax_amount': 642.86, 'tax_p...","{'mode_of_payment': 'CREDIT_CARD', 'modes_from...","{'patient_id': 26322, 'patient_name': 'harneet...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
22,2026-04-11 16:32:39,full body LHR,"{'amount': 45000, 'tax_amount': 2250, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 31802, 'patient_name': 'anushka...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
23,2026-04-11 15:59:46,Balance of full body LHR,"{'amount': 5043, 'tax_amount': 252.19, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 31730, 'patient_name': 'zoha kh...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
24,2026-04-08 18:23:37,full body LHR,"{'amount': 45000, 'tax_amount': 2250, 'tax_per...","{'mode_of_payment': 'SAVEIN', 'modes_from_logs...","{'patient_id': 31730, 'patient_name': 'zoha kh...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
25,2026-04-08 16:28:52,"bodypolishing, hydrafacial","{'amount': 4761, 'tax_amount': 238.1, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 26241, 'patient_name': 'Anupama...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
26,2026-04-08 16:10:06,Balance of full body LHR,"{'amount': 20000, 'tax_amount': 1000, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 31631, 'patient_name': 'kriti w...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
27,2026-04-03 17:12:03,full body LHR,"{'amount': 5714, 'tax_amount': 285.71, 'tax_pe...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 31631, 'patient_name': 'kriti w...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
28,2026-04-02 17:02:42,"UNDERARMS, HALF LEGS","{'amount': 4666, 'tax_amount': 233.33, 'tax_pe...","{'mode_of_payment': 'DEBIT_CARD', 'modes_from_...","{'patient_id': 27795, 'patient_name': 'pathres...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."
29,2026-04-01 17:39:52,full face,"{'amount': 1904, 'tax_amount': 95.24, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 27350, 'patient_name': 'TASREEN...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can..."

In [29]:
df['payment_date'] = pd.to_datetime(df['payment_date'])

df['year'] = df['payment_date'].dt.year
df['month'] = df['payment_date'].dt.month
df['day'] = df['payment_date'].dt.day

df = df.drop(columns=['payment_date'])
df

,package_name,sale,payment,patient,staff,status,transaction_type,source,cancellation,year,month,day
0,Balance of full body LHR,"{'amount': 20000, 'tax_amount': 1000, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 31631, 'patient_name': 'kriti w...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,30
1,chin,"{'amount': 6666, 'tax_amount': 333.33, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 32209, 'patient_name': 'jyoti ....","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,29
2,LOWER FACE LHR,"{'amount': 952, 'tax_amount': 47.62, 'tax_perc...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 26463, 'patient_name': 'Priyank...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,27
3,full face,"{'amount': 7142, 'tax_amount': 357.14, 'tax_pe...","{'mode_of_payment': 'DEBIT_CARD', 'modes_from_...","{'patient_id': 32150, 'patient_name': 'aastha ...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,26
4,full face,"{'amount': 18000, 'tax_amount': 900, 'tax_perc...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 26331, 'patient_name': 'Ishita ...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,25
5,full body LHR,"{'amount': 43809, 'tax_amount': 2190.48, 'tax_...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 26610, 'patient_name': 'TEENA C...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,25
6,"chin, upperlips, neck","{'amount': 1904, 'tax_amount': 95.24, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 32117, 'patient_name': 'ayushi ...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,25
7,full body LHR,"{'amount': 19047, 'tax_amount': 952.38, 'tax_p...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 32094, 'patient_name': 'dolly n...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,24
8,HYDRAFACIAL,"{'amount': 3809, 'tax_amount': 190.48, 'tax_pe...","{'mode_of_payment': 'DEBIT_CARD', 'modes_from_...","{'patient_id': 32081, 'patient_name': 'sahhej ...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,24
9,LOWER FACE LHR,"{'amount': 2380, 'tax_amount': 119.05, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 32059, 'patient_name': 'shradha...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,23
10,full body LHR,"{'amount': 40238, 'tax_amount': 2011.9, 'tax_p...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 32064, 'patient_name': 'Anu kat...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,23
11,Balance of full body LHR,"{'amount': 40238, 'tax_amount': 2011.9, 'tax_p...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 32016, 'patient_name': 'anukrit...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,22
12,full body LHR,"{'amount': 16666, 'tax_amount': 833.33, 'tax_p...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 27762, 'patient_name': 'Priya C...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,22
13,full body LHR,"{'amount': 4761, 'tax_amount': 238.1, 'tax_per...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 32016, 'patient_name': 'anukrit...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,20
14,hydrafacial,"{'amount': 4761, 'tax_amount': 238.1, 'tax_per...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 31968, 'patient_name': 'AKSHITA...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,18
15,LOWER FACE LHR,"{'amount': 7142, 'tax_amount': 357.14, 'tax_pe...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 26351, 'patient_name': 'Kamlesh...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,18
16,kenacort injection,"{'amount': 2380, 'tax_amount': 119.05, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 27362, 'patient_name': 'JYOTSAN...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,18
17,full body LHR,"{'amount': 7619, 'tax_amount': 380.95, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 26239, 'patient_name': 'ANU GUP...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,17
18,"underarms, half legs","{'amount': 4666, 'tax_amount': 233.33, 'tax_pe...","{'mode_of_payment': 'DEBIT_CARD', 'modes_from_...","{'patient_id': 27795, 'patient_name': 'pathres...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,17
19,full body LHR,"{'amount': 9523, 'tax_amount': 476.19, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 1600, 'patient_name': 'Puja Jai...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,13
20,full body LHR,"{'amount': 26190, 'tax_amount': 1309.52, 'tax_...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 31838, 'patient_name': 'prancha...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,13
21,1 hydrafacial and 2 Rf facial,"{'amount': 12857, 'tax_amount': 642.86, 'tax_p...","{'mode_of_payment': 'CREDIT_CARD', 'modes_from...","{'patient_id': 26322, 'patient_name': 'harneet...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,12
22,full body LHR,"{'amount': 45000, 'tax_amount': 2250, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 31802, 'patient_name': 'anushka...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,11
23,Balance of full body LHR,"{'amount': 5043, 'tax_amount': 252.19, 'tax_pe...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 31730, 'patient_name': 'zoha kh...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,11
24,full body LHR,"{'amount': 45000, 'tax_amount': 2250, 'tax_per...","{'mode_of_payment': 'SAVEIN', 'modes_from_logs...","{'patient_id': 31730, 'patient_name': 'zoha kh...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,8
25,"bodypolishing, hydrafacial","{'amount': 4761, 'tax_amount': 238.1, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 26241, 'patient_name': 'Anupama...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,8
26,Balance of full body LHR,"{'amount': 20000, 'tax_amount': 1000, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 31631, 'patient_name': 'kriti w...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,8
27,full body LHR,"{'amount': 5714, 'tax_amount': 285.71, 'tax_pe...","{'mode_of_payment': 'CASH', 'modes_from_logs':...","{'patient_id': 31631, 'patient_name': 'kriti w...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,3
28,"UNDERARMS, HALF LEGS","{'amount': 4666, 'tax_amount': 233.33, 'tax_pe...","{'mode_of_payment': 'DEBIT_CARD', 'modes_from_...","{'patient_id': 27795, 'patient_name': 'pathres...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,2
29,full face,"{'amount': 1904, 'tax_amount': 95.24, 'tax_per...","{'mode_of_payment': 'UPI', 'modes_from_logs': ...","{'patient_id': 27350, 'patient_name': 'TASREEN...","{'id': 53, 'staff_name': 'Hina Kausar', 'mobil...",success,payment,staging,"{'is_cancel': False, 'cancel_date': None, 'can...",2026,4,1

In [30]:
print(df.dtypes)

package_name           str
sale                object
payment             object
patient             object
staff               object
status                 str
transaction_type       str
source                 str
cancellation        object
year                 int32
month                int32
day                  int32
dtype: object

In [31]:
label_encoder = LabelEncoder()

categorical_columns = [
    'package_name',
    'patient',
    'staff',
    'status',
    'transaction_type',
    'source',
    'cancellation',
    'sale',
    'payment'
]

for col in categorical_columns:
    df[col] = label_encoder.fit_transform(df[col].astype(str))

In [32]:
print(df.dtypes)

package_name        int64
sale                int64
payment             int64
patient             int64
staff               int64
status              int64
transaction_type    int64
source              int64
cancellation        int64
year                int32
month               int32
day                 int32
dtype: object

In [33]:
X = df.drop(columns=['cancellation'])

In [34]:
y = df['cancellation']

In [35]:
df

,package_name,sale,payment,patient,staff,status,transaction_type,source,cancellation,year,month,day
0,1,5,4,12,0,0,0,0,0,2026,4,30
1,6,16,4,24,0,0,0,0,0,2026,4,29
2,3,19,0,6,0,0,0,0,0,2026,4,27
3,9,17,2,23,0,0,0,0,0,2026,4,26
4,9,2,4,4,0,0,0,0,0,2026,4,25
5,8,10,4,7,0,0,0,0,0,2026,4,25
6,7,3,4,22,0,0,0,0,0,2026,4,25
7,8,4,0,21,0,0,0,0,0,2026,4,24
8,2,8,2,20,0,0,0,0,0,2026,4,24
9,3,6,4,18,0,0,0,0,0,2026,4,23
10,8,9,4,19,0,0,0,0,0,2026,4,23
11,1,9,0,17,0,0,0,0,0,2026,4,22
12,8,1,4,10,0,0,0,0,0,2026,4,22
13,8,13,0,17,0,0,0,0,0,2026,4,20
14,10,13,0,16,0,0,0,0,0,2026,4,18
15,3,17,0,5,0,0,0,0,0,2026,4,18
16,11,6,4,9,0,0,0,0,0,2026,4,18
17,8,18,4,1,0,0,0,0,0,2026,4,17
18,12,12,2,11,0,0,0,0,0,2026,4,17
19,8,20,4,0,0,0,0,0,0,2026,4,13
20,8,7,4,15,0,0,0,0,0,2026,4,13
21,0,0,1,3,0,0,0,0,0,2026,4,12
22,8,11,4,14,0,0,0,0,0,2026,4,11
23,1,14,4,13,0,0,0,0,0,2026,4,11
24,8,11,3,13,0,0,0,0,0,2026,4,8
25,5,13,4,2,0,0,0,0,0,2026,4,8
26,1,5,4,12,0,0,0,0,0,2026,4,8
27,8,15,0,12,0,0,0,0,0,2026,4,3
28,4,12,2,11,0,0,0,0,0,2026,4,2
29,9,3,4,8,0,0,0,0,0,2026,4,1

In [36]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [37]:
model = XGBClassifier()

model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [38]:
y_pred = model.predict(X_test)

In [39]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 1.0

In [40]:
new_data = X_test.iloc[0:1]

prediction = model.predict(new_data)

prediction

array([0])

In [41]:
df

,package_name,sale,payment,patient,staff,status,transaction_type,source,cancellation,year,month,day
0,1,5,4,12,0,0,0,0,0,2026,4,30
1,6,16,4,24,0,0,0,0,0,2026,4,29
2,3,19,0,6,0,0,0,0,0,2026,4,27
3,9,17,2,23,0,0,0,0,0,2026,4,26
4,9,2,4,4,0,0,0,0,0,2026,4,25
5,8,10,4,7,0,0,0,0,0,2026,4,25
6,7,3,4,22,0,0,0,0,0,2026,4,25
7,8,4,0,21,0,0,0,0,0,2026,4,24
8,2,8,2,20,0,0,0,0,0,2026,4,24
9,3,6,4,18,0,0,0,0,0,2026,4,23
10,8,9,4,19,0,0,0,0,0,2026,4,23
11,1,9,0,17,0,0,0,0,0,2026,4,22
12,8,1,4,10,0,0,0,0,0,2026,4,22
13,8,13,0,17,0,0,0,0,0,2026,4,20
14,10,13,0,16,0,0,0,0,0,2026,4,18
15,3,17,0,5,0,0,0,0,0,2026,4,18
16,11,6,4,9,0,0,0,0,0,2026,4,18
17,8,18,4,1,0,0,0,0,0,2026,4,17
18,12,12,2,11,0,0,0,0,0,2026,4,17
19,8,20,4,0,0,0,0,0,0,2026,4,13
20,8,7,4,15,0,0,0,0,0,2026,4,13
21,0,0,1,3,0,0,0,0,0,2026,4,12
22,8,11,4,14,0,0,0,0,0,2026,4,11
23,1,14,4,13,0,0,0,0,0,2026,4,11
24,8,11,3,13,0,0,0,0,0,2026,4,8
25,5,13,4,2,0,0,0,0,0,2026,4,8
26,1,5,4,12,0,0,0,0,0,2026,4,8
27,8,15,0,12,0,0,0,0,0,2026,4,3
28,4,12,2,11,0,0,0,0,0,2026,4,2
29,9,3,4,8,0,0,0,0,0,2026,4,1

In [42]:
le = LabelEncoder()

df['cancellation'] = le.fit_transform(df['cancellation'])

print(le.classes_)

[0]

In [43]:
prediction = model.predict(new_data)

print(le.inverse_transform(prediction))

[0]

In [44]:
prediction

array([0])