In [45]:

import pandas as pd
from sklearn.preprocessing import LabelEncoder 
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [46]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

In [47]:
df = pd.read_csv(url)
df

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [48]:
print(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [49]:
dg = df.isnull().sum()
print(dg)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [50]:
df["Age"].fillna(df["Age"].mean(), inplace = True )
print(df)

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

C:\Users\ayush\AppData\Local\Temp\ipykernel_20284\587083476.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Age"].fillna(df["Age"].mean(), inplace = True )

In [51]:
dn = df["Embarked"].fillna(df["Embarked"].mode()[0])
dn.head()

0    S
1    C
2    S
3    S
4    S
Name: Embarked, dtype: str

In [52]:
dg = df.drop("Cabin", axis= 1, inplace =True )

In [53]:
le = LabelEncoder()

df["Sex_labled"]= le.fit_transform(df["Sex"])

print(df[["Name","Sex", "Sex_labled"]])

                                                  Name     Sex  Sex_labled
0                              Braund, Mr. Owen Harris    male           1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female           0
2                               Heikkinen, Miss. Laina  female           0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female           0
4                             Allen, Mr. William Henry    male           1
..                                                 ...     ...         ...
886                              Montvila, Rev. Juozas    male           1
887                       Graham, Miss. Margaret Edith  female           0
888           Johnston, Miss. Catherine Helen "Carrie"  female           0
889                              Behr, Mr. Karl Howell    male           1
890                                Dooley, Mr. Patrick    male           1

[891 rows x 3 columns]

In [54]:
print(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked', 'Sex_labled'],
      dtype='str')

In [55]:
df_encoded = pd.get_dummies(df, columns=["Embarked"])
df_encoded

     PassengerId  Survived  Pclass  ... Embarked_C Embarked_Q  Embarked_S
0              1         0       3  ...      False      False        True
1              2         1       1  ...       True      False       False
2              3         1       3  ...      False      False        True
3              4         1       1  ...      False      False        True
4              5         0       3  ...      False      False        True
..           ...       ...     ...  ...        ...        ...         ...
886          887         0       2  ...      False      False        True
887          888         1       1  ...      False      False        True
888          889         0       3  ...      False      False        True
889          890         1       1  ...       True      False       False
890          891         0       3  ...      False       True       False

[891 rows x 14 columns]

In [56]:
le = LabelEncoder()
df_encoded["Embarkedc"]= le.fit_transform(df_encoded["Embarked_C"])
df_encoded["Embarkedq"]= le.fit_transform(df_encoded["Embarked_Q"])
df_encoded["Embarkeds"]= le.fit_transform(df_encoded["Embarked_S"])

df_encoded[["Embarked_C", "Embarkedc", "Embarked_Q","Embarkedq", "Embarked_S", "Embarkeds"]]

df_encoded["Age"].fillna(df_encoded["Age"].mean(), inplace = True)

C:\Users\ayush\AppData\Local\Temp\ipykernel_20284\2266031905.py:8: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_encoded["Age"].fillna(df_encoded["Age"].mean(), inplace = True)

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [57]:
std = StandardScaler()
std_scale = std.fit_transform(df[["Age", "Fare"]])
df_scaled = pd.DataFrame(std_scale , columns=[["Age","Fare"]])
df_scaled

          Age      Fare
0   -0.530377 -0.502445
1    0.571831  0.786845
2   -0.254825 -0.488854
3    0.365167  0.420730
4    0.365167 -0.486337
..        ...       ...
886 -0.185937 -0.386671
887 -0.737041 -0.044381
888       NaN -0.176263
889 -0.254825 -0.044381
890  0.158503 -0.492378

[891 rows x 2 columns]

In [64]:
X = df_encoded[["Pclass", "Sex_labled","Age", "SibSp", "Parch", "Embarkedc", "Embarkedq", "Embarkeds"]]
y= df_encoded[["Survived"]]

X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2, random_state =42)



print("y after training")
print(y_train)

print("y after testing")
print(y_test)

y after training
     Survived
331         0
733         0
382         0
704         0
813         0
..        ...
106         1
270         0
860         0
435         1
102         0

[712 rows x 1 columns]
y after testing
     Survived
709         1
439         0
840         0
720         1
39          1
..        ...
433         0
773         0
25          1
84          1
10          1

[179 rows x 1 columns]

In [59]:
print(df_encoded.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Sex_labled       0
Embarked_C       0
Embarked_Q       0
Embarked_S       0
Embarkedc        0
Embarkedq        0
Embarkeds        0
dtype: int64

In [61]:
df_encoded["Age"].fillna(df_encoded["Age"].mean(), inplace = True)

C:\Users\ayush\AppData\Local\Temp\ipykernel_20284\1334660507.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_encoded["Age"].fillna(df_encoded["Age"].mean(), inplace = True)

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [62]:
df_encoded

     PassengerId  Survived  Pclass  ... Embarkedc Embarkedq  Embarkeds
0              1         0       3  ...         0         0          1
1              2         1       1  ...         1         0          0
2              3         1       3  ...         0         0          1
3              4         1       1  ...         0         0          1
4              5         0       3  ...         0         0          1
..           ...       ...     ...  ...       ...       ...        ...
886          887         0       2  ...         0         0          1
887          888         1       1  ...         0         0          1
888          889         0       3  ...         0         0          1
889          890         1       1  ...         1         0          0
890          891         0       3  ...         0         1          0

[891 rows x 17 columns]